// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Task struct {
	ID         string         `json:"id"`
	Mode       string         `json:"mode"`
	TargetHost string         `json:"target_host"`
	TargetPort sql.NullInt32  `json:"target_port"`
	Brief      sql.NullString `json:"brief"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
