// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	// 统计指定状态的任务数量
	CountTasksByStatus(ctx context.Context, status string) (int64, error)
	// 创建新任务
	CreateTask(ctx context.Context, iD string, mode string, targetHost string, targetPort sql.NullInt32, brief sql.NullString, status string, createdAt time.Time, updatedAt time.Time) (Task, error)
	// 删除任务
	DeleteTask(ctx context.Context, id string) error
	// sql/queries/task.sql
	// 任务相关的查询（示例）
	// 根据 ID 获取任务
	GetTaskByID(ctx context.Context, id string) (Task, error)
	// 列出所有任务
	ListTasks(ctx context.Context, limit int32, offset int32) ([]Task, error)
	// 根据状态列出任务
	ListTasksByStatus(ctx context.Context, status string) ([]Task, error)
	// 更新任务状态
	UpdateTaskStatus(ctx context.Context, iD string, status string, updatedAt time.Time) error
}

var _ Querier = (*Queries)(nil)
