// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countTasksByStatus = `-- name: CountTasksByStatus :one
SELECT COUNT(*) FROM task
WHERE status = $1
`

// 统计指定状态的任务数量
func (q *Queries) CountTasksByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO task (
    id, mode, target_host, target_port, brief, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, mode, target_host, target_port, brief, status, created_at, updated_at
`

// 创建新任务
func (q *Queries) CreateTask(ctx context.Context, iD string, mode string, targetHost string, targetPort sql.NullInt32, brief sql.NullString, status string, createdAt time.Time, updatedAt time.Time) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		iD,
		mode,
		targetHost,
		targetPort,
		brief,
		status,
		createdAt,
		updatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.TargetHost,
		&i.TargetPort,
		&i.Brief,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM task
WHERE id = $1
`

// 删除任务
func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one

SELECT id, mode, target_host, target_port, brief, status, created_at, updated_at FROM task
WHERE id = $1
`

// sql/queries/task.sql
// 任务相关的查询（示例）
// 根据 ID 获取任务
func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.TargetHost,
		&i.TargetPort,
		&i.Brief,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, mode, target_host, target_port, brief, status, created_at, updated_at FROM task
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

// 列出所有任务
func (q *Queries) ListTasks(ctx context.Context, limit int32, offset int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.TargetHost,
			&i.TargetPort,
			&i.Brief,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, mode, target_host, target_port, brief, status, created_at, updated_at FROM task
WHERE status = $1
ORDER BY created_at DESC
`

// 根据状态列出任务
func (q *Queries) ListTasksByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.TargetHost,
			&i.TargetPort,
			&i.Brief,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE task
SET status = $2, updated_at = $3
WHERE id = $1
`

// 更新任务状态
func (q *Queries) UpdateTaskStatus(ctx context.Context, iD string, status string, updatedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, iD, status, updatedAt)
	return err
}
